### ISSUE TITLE
Allow custom table names

### ISSUE THREAD

**Issue by fams** [curityio/dynamodb-data-access-provider#7]
Dynamo DB has no namespace concept like instances or directories.  The plugin configuration needs to provide a way to define custom table names to allow two DyanmoDB data-source facilities in the same account.

**Comment by pmhsfelix** [comment]
The support for the configuration of tables names was added on version bundled in the 6.4.0 version of Curity Identity Server - https://developer.curity.io/release/6.4.0/release-notes
See 97b62235203f4bb192acd67eda9fc0b0570e824d
Sorry for the delay on updating this issue.
